// app/layout.tsx
import type { Metadata } from 'next';
import { Inter, Sukhumvit_Set } from 'next/font/google';
import './globals.css';

// เพิ่มฟอนต์ Sukhumvit Set สำหรับภาษาไทย
const sukhumvitSet = Sukhumvit_Set({
  weight: ['400', '700'],
  subsets: ['thai'],
  variable: '--font-sukhumvit',
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
      <body className={`${sukhumvitSet.variable} ${inter.className} font-sans`}>
        {children}
      </body>
    </html>
  );
}